<?php

use Drupal\wmentity_overview\Annotation\OverviewBuilder;
use Drupal\wmentity_overview\Event\EntityOverviewAlterEvent;
use Drupal\wmentity_overview\Event\EntityOverviewAlternativesAlterEvent;
use Drupal\wmentity_overview\WmEntityOverviewEvents;

function wmentity_overview_entity_overview_alter(array &$overview, OverviewBuilder $definition)
{
    $dispatcher = \Drupal::getContainer()->get('event_dispatcher');
    $event = new EntityOverviewAlterEvent($definition, $overview);

    $dispatcher->dispatch(WmEntityOverviewEvents::ENTITY_OVERVIEW_ALTER, $event);
}


function wmentity_overview_entity_overview_alternatives_alter(array &$alternatives, OverviewBuilder $definition)
{
    $dispatcher = \Drupal::getContainer()->get('event_dispatcher');
    $event = new EntityOverviewAlternativesAlterEvent($definition, $alternatives);

    $dispatcher->dispatch(WmEntityOverviewEvents::ENTITY_OVERVIEW_ALTERNATIVES_ALTER, $event);
}


/**
 * Implements @see hook_library_info_alter().
 */
function wmentity_overview_library_info_alter(array &$libraries, string $extension): void
{
    if ($extension !== 'wmentity_overview') {
        return;
    }

    if (_wmentity_overview_theme_is_active('gin')) {
        $libraries['tooltip']['css']['theme']['css/tooltip-gin.css'] = [];
    }
}

function _wmentity_overview_theme_is_active(string $themeNameToCheck)
{
    $themeHandler = \Drupal::service('theme_handler')->listInfo();
    $themeConfig = \Drupal::config('system.theme');
    $themeNames = [];

    foreach (['default', 'admin'] as $type) {
        if (!$themeName = $themeConfig->get($type)) {
            continue;
        }

        $themeNames[$themeName] = $themeName;

        if (isset($themeHandler[$themeName]->base_themes)) {
            $themeNames = array_merge($themeNames, $themeHandler[$themeName]->base_themes);
        }
    }

    return array_key_exists($themeNameToCheck, $themeNames);
}
