<?php

use Drupal\wmentity_overview\Annotation\OverviewBuilder;
use Drupal\wmentity_overview\Event\EntityOverviewAlterEvent;
use Drupal\wmentity_overview\Event\EntityOverviewAlternativesAlterEvent;
use Drupal\wmentity_overview\WmEntityOverviewEvents;

function wmentity_overview_entity_overview_alter(array &$overview, OverviewBuilder $definition)
{
    $dispatcher = \Drupal::getContainer()->get('event_dispatcher');
    $event = new EntityOverviewAlterEvent($definition, $overview);

    $dispatcher->dispatch(WmEntityOverviewEvents::ENTITY_OVERVIEW_ALTER, $event);
}


function wmentity_overview_entity_overview_alternatives_alter(array &$alternatives, OverviewBuilder $definition)
{
    $dispatcher = \Drupal::getContainer()->get('event_dispatcher');
    $event = new EntityOverviewAlternativesAlterEvent($definition, $alternatives);

    $dispatcher->dispatch(WmEntityOverviewEvents::ENTITY_OVERVIEW_ALTERNATIVES_ALTER, $event);
}
